In [4]:
import pandas as pd
import numpy as np
import plotly.express as px
import matplotlib.pyplot as plt
from matplotlib.dates import DateFormatter
plt.style.use('seaborn-whitegrid')
import matplotlib as mpl
mpl.rc("figure", facecolor="white")
#print(plt.style.available)
import plotly.io as pio
import seaborn as sns
sns.set(style='whitegrid')
sns.set_palette('bright')
#sns.set(rc={'figure.figsize':(10,8)})
pio.templates.default = "none"

In [5]:
df = pd.read_csv(f'Precipitation data(csv)/MasterData.csv')
df

       Unnamed: 0                 Date  precipitationCal
0               0  2018-06-01 00:00:00             0.036
1               1  2018-06-01 00:30:00             0.056
2               2  2018-06-01 01:00:00             0.065
3               3  2018-06-01 01:30:00             0.051
4               4  2018-06-01 02:00:00             0.030
...           ...                  ...               ...
11995       11995  2020-08-10 21:30:00             1.841
11996       11996  2020-08-10 22:00:00             1.599
11997       11997  2020-08-10 22:30:00             2.377
11998       11998  2020-08-10 23:00:00             2.321
11999       11999  2020-08-10 23:30:00             2.251

[12000 rows x 3 columns]